## Use workflows from ninenines/ci.erlang.mk to test Gun.

name: Check Gun

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 2am.
      - cron: 0 2 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cleanup-master:
    name: Cleanup master build
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:

    - name: Cleanup master build if necessary
      if: ${{ github.event_name == 'schedule' }}
      run: |
        gh cache delete Linux-X64-Erlang-master -R $REPO || true
        gh cache delete macOS-ARM64-Erlang-master -R $REPO || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}

  check:
    name: Gun
    needs: cleanup-master
    uses: ninenines/ci.erlang.mk/.github/workflows/ci.yaml@master
